uploads = []
generated = []

[[outputs]]
id = "x6nnVf4Di6xDjDI95AIWg"
uri = "file://youme_flutter.zip"
type = "unspecified"
title = "YouMe — Projet Flutter complet"

[[outputs]]
id = "87tgKlKixrFs53I0ZsQ4E"
uri = "file://flutter_youme.zip"
type = "unspecified"
title = "YouMe – Projet Flutter Tropical Paradise"

[[outputs]]
id = "e6lumkPMaGne2Bm14rLNo"
uri = "file://youme-flutter-secured.zip"
type = "unspecified"
title = "YouMe — Projet complet sécurisé"

[[outputs]]
id = "HlxbWcAdvO3ntqTdGOyoH"
uri = "file://youme-release.keystore"
type = "unspecified"
title = "youme-release.keystore — À sauvegarder précieusement"

[[outputs]]
id = "n1ygR95OBVGygh4M2KNfM"
uri = "file://youme-complet.zip"
type = "unspecified"
title = "YouMe — Tous les fichiers (projet + keystore)"
