uploads = []
generated = []

[[outputs]]
id = "x6nnVf4Di6xDjDI95AIWg"
uri = "file://youme_flutter.zip"
type = "unspecified"
title = "YouMe — Projet Flutter complet"

[[outputs]]
id = "87tgKlKixrFs53I0ZsQ4E"
uri = "file://flutter_youme.zip"
type = "unspecified"
title = "YouMe – Projet Flutter Tropical Paradise"
